buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath "gradle.plugin.com.github.johnrengelman:shadow:7.1.2"
    }
}

plugins {
    id "java"
    id "com.github.johnrengelman.shadow" version "7.1.2"
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

version = "0.0.1"

repositories {
    mavenCentral()
    maven {
        url "https://packages.confluent.io/maven"
    }
}

dependencies {
    implementation 'io.confluent.ksql:ksql-udf:5.4.11'
    implementation "org.apache.kafka:kafka_2.13:2.5.0"
    implementation "org.apache.kafka:connect-api:2.5.0"
    implementation 'org.json:json:20250107'
    testImplementation 'junit:junit:4.13.2'
}

compileJava {
    options.compilerArgs << "-parameters"
}

shadowJar {
    archiveBaseName = "ksqldb-custom-udfs"
    archiveClassifier = ""
    destinationDirectory = file("udfjar")
}
